mrn:
  - mrn
  - medrec
  - medrec#
  - mrnum
  - medical record number
  - medical #
  - patient id
  - patient #
  - patient identifier

first_name:
  - first_name
  - fname
  - first
  - f name
  - given name
  
last_name:
  - last_name
  - lname
  - last
  - l name
  - surname
  - family name
  - last_name__c_sf

dob:
  - dob
  - date_of_birth
  - date of birth
  - birthdate
  - birth date
  - dob__c_sf
  - patient_date_of_birth_date_time_mysql

gender:
  - gender
  - sex

address:
  - address
  - addr
  - addr.
  - home address
  - office address

practice_guid:
  - practice_guid
  - practice_guid__c
  - practiceguid
  - practice_guidc
  - practice_guid_sf
  - practice_guid_mysql
  

